repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1
  gwt_user: com.google.gwt:gwt-user:jar:2.5.1
  gwt_dev: com.google.gwt:gwt-dev:jar:2.5.1

  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  #
  # GIN and associated dependencies
  javax_inject: javax.inject:javax.inject:jar:1
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  gwt_voices: com.allen-sauer.gwt.voices:gwt-voices:jar:3.2.0

  gwt_cache_filter: org.realityforge.gwt.cache-filter:gwt-cache-filter:jar:0.3

  gwt_appcache_client: org.realityforge.gwt.appcache:gwt-appcache-client:jar:1.0.2
  gwt_appcache_linker: org.realityforge.gwt.appcache:gwt-appcache-linker:jar:1.0.2
  gwt_appcache_server: org.realityforge.gwt.appcache:gwt-appcache-server:jar:1.0.2
